name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Python Post Requests tests
      id: python-post-requests-tests
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 100
        setup-command: pip install pytest requests && cd ./src && flask run --host=localhost
          --port=5000 & && cd ../tests
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTHON-POST-REQUESTS-TESTS_RESULTS: "${{steps.python-post-requests-tests.outputs.result}}"
      with:
        runners: python-post-requests-tests
